apiVersion: v1
kind: Service
metadata:
  annotations:
    aliyun/clb_id: "lb-bp117qz1mztx0r64oo6eg"
    aliyun/clb_port: "80"
    aliyun/vpc_id: "vpc-bp1km8lhqausyndk3gwol"
    aliyun/regionid: "cn-hangzhou"
  name: my-service
  labels:
    app: my-app
spec:
  type: NodePort
  ports:
  - port: 802
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: my-app